// <auto-generated />
using CPK_Bot.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPK_Bot.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20240715054313_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CPK_Bot.Models.BackendQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.ToTable("BackendQuestions");
                });

            modelBuilder.Entity("CPK_Bot.Models.FrontendQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.ToTable("FrontendQuestions");
                });

            modelBuilder.Entity("CPK_Bot.Models.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
